name: Build and Package pyMeow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install Nim language (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install nim

    - name: Install Nim language (Linux)
      if: runner.os == 'Linux'
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
        echo "export PATH=$HOME/.nimble/bin:$PATH" >> $GITHUB_ENV

    - name: Build nimlib (Windows)
      if: runner.os == 'Windows'
      run: |
        nimble build -d:release --passL:"-static" -o:pyMeow.pyd pyMeow.nim

    - name: Build nimlib (Linux)
      if: runner.os == 'Linux'
      run: |
        nimble build -d:release --passL:"-static" -o:pyMeow.so pyMeow.nim

    - name: Move nimlib to pyMeow folder (Windows)
      if: runner.os == 'Windows'
      run: |
        Move-Item src\pyMeow.pyd pyMeow\pyMeow\

    - name: Move nimlib to pyMeow folder (Linux)
      if: runner.os == 'Linux'
      run: |
        mv src/pyMeow.so pyMeow/pyMeow/

    - name: Build python package
      run: |
        python setup.py sdist bdist_wheel
